# Generated by Django 4.2.29 on 2026-03-13 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dossiers", "0002_dossier_metadata"),
        ("documents", "0006_document_visibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("protocols", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformationPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("PdV", "Versamento"),
                            ("PdA", "Archiviazione"),
                            ("PdD", "Distribuzione"),
                        ],
                        max_length=10,
                    ),
                ),
                ("package_id", models.CharField(max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "package_file",
                    models.FileField(
                        blank=True, null=True, upload_to="packages/%Y/%m/"
                    ),
                ),
                (
                    "manifest_file",
                    models.FileField(
                        blank=True, null=True, upload_to="packages/%Y/%m/"
                    ),
                ),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("timestamp_token", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bozza"),
                            ("ready", "Pronto"),
                            ("sent", "Inviato"),
                            ("accepted", "Accettato"),
                            ("rejected", "Rifiutato"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("conservation_response", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pacchetto informativo",
                "verbose_name_plural": "Pacchetti informativi",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RetentionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("classification_code", models.CharField(max_length=50, unique=True)),
                ("classification_label", models.CharField(max_length=200)),
                ("document_types", models.JSONField(blank=True, default=list)),
                ("retention_years", models.IntegerField()),
                ("retention_basis", models.CharField(blank=True, max_length=500)),
                (
                    "action_after_retention",
                    models.CharField(
                        choices=[
                            ("discard", "Scarto"),
                            ("permanent_preserve", "Conservazione permanente"),
                            ("review", "Revisione"),
                        ],
                        default="review",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Regola di conservazione",
                "verbose_name_plural": "Regole di conservazione",
                "ordering": ["classification_code"],
            },
        ),
        migrations.CreateModel(
            name="PackageProtocolLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_protocol_links",
                        to="archive.informationpackage",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_protocol_links",
                        to="protocols.protocol",
                    ),
                ),
            ],
            options={
                "unique_together": {("package", "protocol")},
            },
        ),
        migrations.CreateModel(
            name="PackageDossierLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_dossier_links",
                        to="dossiers.dossier",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_dossier_links",
                        to="archive.informationpackage",
                    ),
                ),
            ],
            options={
                "unique_together": {("package", "dossier")},
            },
        ),
        migrations.CreateModel(
            name="PackageDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metadata_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_links",
                        to="documents.document",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_documents",
                        to="archive.informationpackage",
                    ),
                ),
            ],
            options={
                "unique_together": {("package", "document")},
            },
        ),
        migrations.AddField(
            model_name="informationpackage",
            name="documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="information_packages",
                through="archive.PackageDocument",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="informationpackage",
            name="dossiers",
            field=models.ManyToManyField(
                blank=True,
                related_name="information_packages",
                through="archive.PackageDossierLink",
                to="dossiers.dossier",
            ),
        ),
        migrations.AddField(
            model_name="informationpackage",
            name="protocols",
            field=models.ManyToManyField(
                blank=True,
                related_name="information_packages",
                through="archive.PackageProtocolLink",
                to="protocols.protocol",
            ),
        ),
        migrations.CreateModel(
            name="DocumentArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("current", "Archivio Corrente"),
                            ("deposit", "Archivio di Deposito"),
                            ("historical", "Archivio Storico"),
                        ],
                        default="current",
                        max_length=20,
                    ),
                ),
                ("classification_code", models.CharField(blank=True, max_length=50)),
                ("classification_label", models.CharField(blank=True, max_length=200)),
                ("retention_years", models.IntegerField(default=10)),
                ("retention_rule", models.CharField(blank=True, max_length=200)),
                ("archive_date", models.DateTimeField(blank=True, null=True)),
                ("historical_date", models.DateTimeField(blank=True, null=True)),
                ("discard_date", models.DateField(blank=True, null=True)),
                ("discard_approved", models.BooleanField(default=False)),
                (
                    "conservation_package_id",
                    models.CharField(blank=True, max_length=200),
                ),
                ("conservation_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conservation_status",
                    models.CharField(
                        choices=[
                            ("not_sent", "Non inviato"),
                            ("pending", "In attesa"),
                            ("accepted", "Accettato"),
                            ("rejected", "Rifiutato"),
                        ],
                        default="not_sent",
                        max_length=20,
                    ),
                ),
                ("conservation_response", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archive_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_record",
                        to="documents.document",
                    ),
                ),
                (
                    "historical_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historical_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Record archivistico",
                "verbose_name_plural": "Record archivistici",
                "ordering": ["-updated_at"],
            },
        ),
    ]
