# Generated by Django 4.2.29 on 2026-03-25 18:56

import apps.sharing.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_tenant_organizationalunit_tenant"),
        ("sharing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharelink",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_links",
                to="organizations.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="token",
            field=models.CharField(
                db_index=True,
                default=apps.sharing.models._default_token,
                max_length=64,
                unique=True,
            ),
        ),
    ]
