# Generated by Django 4.2.29 on 2026-03-12 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetadataStructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "allowed_file_extensions",
                    models.JSONField(
                        default=list,
                        help_text="Lista estensioni es. ['.pdf', '.docx']. Vuoto = tutti.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_metadata_structures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Struttura metadati",
                "verbose_name_plural": "Strutture metadati",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MetadataStructureOU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organizational_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_metadata_structures",
                        to="organizations.organizationalunit",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_organizational_units",
                        to="metadata.metadatastructure",
                    ),
                ),
            ],
            options={
                "verbose_name": "UO consentita per struttura",
                "verbose_name_plural": "UO consentite per struttura",
                "unique_together": {("structure", "organizational_unit")},
            },
        ),
        migrations.CreateModel(
            name="MetadataField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("label", models.CharField(max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Testo libero"),
                            ("number", "Numero"),
                            ("date", "Data"),
                            ("datetime", "Data e ora"),
                            ("boolean", "Sì/No"),
                            ("select", "Selezione singola"),
                            ("multiselect", "Selezione multipla"),
                            ("email", "Email"),
                            ("phone", "Telefono"),
                            ("textarea", "Testo lungo"),
                            ("url", "URL"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_searchable", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "options",
                    models.JSONField(
                        default=list,
                        help_text='Per select/multiselect: [{"value": "v1", "label": "Label 1"}, ...]',
                    ),
                ),
                ("default_value", models.JSONField(blank=True, null=True)),
                (
                    "validation_rules",
                    models.JSONField(
                        default=dict,
                        help_text='Es: {"min": 0, "max": 100} per number; {"regex": "..."} per text',
                    ),
                ),
                ("help_text", models.CharField(blank=True, max_length=500)),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="metadata.metadatastructure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campo metadato",
                "verbose_name_plural": "Campi metadato",
                "ordering": ["order", "name"],
                "unique_together": {("structure", "name")},
            },
        ),
    ]
