# Generated by Django 4.2.29 on 2026-03-12 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("metadata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadatastructure",
            name="allowed_signers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Firmatari autorizzati per questa struttura. Vuoto = tutti gli APPROVER.",
                related_name="metadata_structures_as_allowed_signer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="metadatastructure",
            name="conservation_class",
            field=models.CharField(default="1", max_length=10),
        ),
        migrations.AddField(
            model_name="metadatastructure",
            name="conservation_document_type",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="metadatastructure",
            name="conservation_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="metadatastructure",
            name="signature_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Se True, i documenti di questo tipo possono essere firmati.",
            ),
        ),
        migrations.AddField(
            model_name="metadatastructure",
            name="signature_format",
            field=models.CharField(
                choices=[
                    ("cades", "CAdES (.p7m)"),
                    ("pades_invisible", "PAdES invisibile"),
                    ("pades_graphic", "PAdES grafica"),
                ],
                default="pades_invisible",
                max_length=20,
            ),
        ),
    ]
