# Generated by Django 4.2.29 on 2026-03-25 17:38

import apps.metadata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0003_applicable_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadatastructure",
            name="applicable_to",
            field=models.JSONField(
                blank=True,
                default=apps.metadata.models.default_applicable_to,
                help_text="Tipi entità: 'document', 'folder', 'dossier', 'email'. Default: ['document'].",
            ),
        ),
    ]
