# Generated by Django 4.2.29 on 2026-03-25 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="accountable_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Responsabile finale (Accountable) dello step",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accountable_workflow_steps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="consulted_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Utenti da consultare prima dell'azione",
                related_name="consulted_workflow_steps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="informed_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Utenti da informare dopo il completamento",
                related_name="informed_workflow_steps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="consulted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="consulted_responses",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="informed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
