# Generated by Django 4.2.29 on 2026-03-25 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_tenant_organizationalunit_tenant"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="organizations.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("workflow_assigned", "Workflow assegnato"),
                    ("workflow_approved", "Documento approvato"),
                    ("workflow_rejected", "Documento rifiutato"),
                    ("workflow_changes_requested", "Modifiche richieste"),
                    ("workflow_completed", "Workflow completato"),
                    ("document_shared", "Documento condiviso"),
                    ("mention", "Menzione"),
                    ("system", "Sistema"),
                    ("signature_requested", "Firma richiesta"),
                    ("signature_completed", "Firma completata"),
                    ("signature_rejected", "Firma rifiutata"),
                    ("signature_step_completed", "Step firma completato"),
                ],
                max_length=40,
            ),
        ),
    ]
