# Generated by Django 4.2.29 on 2026-03-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0004_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroup",
            name="organizational_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Unità organizzativa di appartenenza del gruppo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="organizations.organizationalunit",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
    ]
