# Generated by Django 4.2.29 on 2026-03-25 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_tenant_organizationalunit_tenant"),
        ("users", "0006_consentrecord_user_gdpr_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="consentrecord",
            new_name="users_conse_user_id_c47983_idx",
            old_name="usr_consent_usr_typ_idx",
        ),
        migrations.AddField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="organizations.tenant",
            ),
        ),
        migrations.AddField(
            model_name="usergroup",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_groups",
                to="organizations.tenant",
            ),
        ),
    ]
