# Generated by Django 4.2.29 on 2026-03-25 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[("person", "Persona"), ("company", "Azienda/Ente")],
                        default="person",
                        max_length=10,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=200)),
                ("last_name", models.CharField(blank=True, max_length=200)),
                (
                    "company_name",
                    models.CharField(
                        blank=True, help_text="Nome azienda/ente", max_length=300
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, help_text="Ruolo/qualifica", max_length=200
                    ),
                ),
                (
                    "tax_code",
                    models.CharField(
                        blank=True, help_text="Codice fiscale / P.IVA", max_length=20
                    ),
                ),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("pec", models.EmailField(blank=True, help_text="PEC", max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("mobile", models.CharField(blank=True, max_length=30)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("province", models.CharField(blank=True, max_length=5)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                (
                    "country",
                    models.CharField(blank=True, default="Italia", max_length=100),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text='["fornitore", "cliente"]'
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "is_shared",
                    models.BooleanField(
                        default=True, help_text="Visibile a tutti gli utenti"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="manual",
                        help_text="manual | mail_import | protocol",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizational_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="U.O. proprietaria del contatto",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts",
                        to="organizations.organizationalunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contatto",
                "verbose_name_plural": "Contatti",
                "ordering": ["last_name", "first_name", "company_name"],
            },
        ),
    ]
