# Generated by Django 4.2.29 on 2026-03-26 10:45

import apps.authentication.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=apps.authentication.encryption.EncryptedCharField(
                blank=True, max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="mobile",
            field=apps.authentication.encryption.EncryptedCharField(
                blank=True, max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="pec",
            field=apps.authentication.encryption.EncryptedCharField(
                blank=True, help_text="PEC", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=apps.authentication.encryption.EncryptedCharField(
                blank=True, max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="tax_code",
            field=apps.authentication.encryption.EncryptedCharField(
                blank=True, help_text="Codice fiscale / P.IVA", max_length=20
            ),
        ),
    ]
