# Generated by Django 4.2.29 on 2026-03-13 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0006_document_visibility"),
        ("dossiers", "0002_dossier_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="archive_stage",
            field=models.CharField(
                choices=[
                    ("current", "Corrente"),
                    ("deposit", "Deposito"),
                    ("historical", "Storico"),
                ],
                default="current",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="classification_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="dossier",
            name="classification_label",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="dossier",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dossier",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_dossiers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="index_file",
            field=models.FileField(
                blank=True, null=True, upload_to="dossiers/indexes/%Y/"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="index_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dossier",
            name="organizational_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="UO per generazione codice identificativo ANNO/UO/PROG.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dossiers",
                to="organizations.organizationalunit",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="retention_basis",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="dossier",
            name="retention_years",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="identifier",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="DossierFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="dossiers/files/%Y/%m/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(default=0)),
                ("file_type", models.CharField(blank=True, max_length=100)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossier_files",
                        to="dossiers.dossier",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossier_files_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DossierEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[("pec", "PEC"), ("email", "Email"), ("peo", "PEO")],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("from_address", models.EmailField(max_length=254)),
                ("to_addresses", models.JSONField(blank=True, default=list)),
                ("subject", models.CharField(max_length=500)),
                ("body", models.TextField(blank=True)),
                ("received_at", models.DateTimeField()),
                ("message_id", models.CharField(blank=True, max_length=500)),
                (
                    "raw_file",
                    models.FileField(
                        blank=True, null=True, upload_to="dossiers/emails/%Y/%m/"
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossier_emails_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossier_emails",
                        to="dossiers.dossier",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="DossierFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossier_folders_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossier_folders",
                        to="dossiers.dossier",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossier_links",
                        to="documents.folder",
                    ),
                ),
            ],
            options={
                "unique_together": {("dossier", "folder")},
            },
        ),
    ]
