# Generated by Django 4.2.29 on 2026-03-25 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_tenant_organizationalunit_tenant"),
        ("authentication", "0002_userinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="organizations.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGIN_FAILED", "Login Fallito"),
                    ("LOGOUT", "Logout"),
                    ("PASSWORD_RESET", "Reset Password"),
                    ("PASSWORD_CHANGED", "Password Cambiata"),
                    ("USER_CREATED", "Utente Creato"),
                    ("USERS_IMPORTED", "Import utenti"),
                    ("USER_UPDATED", "Utente Modificato"),
                    ("USER_INVITED", "Invito Inviato"),
                    ("INVITATION_ACCEPTED", "Invito Accettato"),
                    ("DOCUMENT_CREATED", "Documento Creato"),
                    ("DOCUMENT_UPLOADED", "Documento Caricato"),
                    ("DOCUMENT_DOWNLOADED", "Documento Scaricato"),
                    ("DOCUMENT_DELETED", "Documento Eliminato"),
                    ("DOCUMENT_SHARED", "Documento Condiviso"),
                    ("WORKFLOW_STARTED", "Workflow Avviato"),
                    ("WORKFLOW_APPROVED", "Documento Approvato"),
                    ("WORKFLOW_REJECTED", "Documento Rifiutato"),
                    ("PROTOCOL_CREATED", "Protocollo Creato"),
                    ("DOCUMENT_SIGNED", "Documento Firmato"),
                    ("DOCUMENT_CONSERVED", "Documento in Conservazione"),
                    ("DOCUMENT_ENCRYPTED", "Documento Cifrato"),
                    ("USER_ANONYMIZED", "Utente anonimizzato"),
                ],
                max_length=50,
            ),
        ),
    ]
