# Generated by Django 4.2.29 on 2026-03-25 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_tenant_organizationalunit_tenant"),
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mailmessage",
            new_name="mail_mailme_account_80627c_idx",
            old_name="mail_msg_acc_fld_sent",
        ),
        migrations.RenameIndex(
            model_name="mailmessage",
            new_name="mail_mailme_message_beb455_idx",
            old_name="mail_msg_message_id",
        ),
        migrations.AddField(
            model_name="mailaccount",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mail_accounts",
                to="organizations.tenant",
            ),
        ),
    ]
