# Generated by Django 4.2.29 on 2026-03-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemLicense",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("organization_name", models.CharField(max_length=500)),
                ("license_key", models.CharField(blank=True, max_length=500)),
                ("activated_at", models.DateField(blank=True, null=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("max_users", models.IntegerField(blank=True, null=True)),
                ("max_storage_gb", models.FloatField(blank=True, null=True)),
                (
                    "features_enabled",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Es: {"mfa": true, "sso": false, "ldap": true, ...}',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Licenza di sistema",
                "verbose_name_plural": "Licenze di sistema",
            },
        ),
    ]
