# Generated by Django 4.2.29 on 2026-03-12 15:59
# FASE 06: FK da documents.MetadataStructure a metadata.MetadataStructure

from django.db import migrations, models
import django.db.models.deletion


def clear_metadata_structure_fk(apps, schema_editor):
    """Azzera FK prima di puntare alla nuova app metadata (vecchi ID non validi)."""
    Document = apps.get_model("documents", "Document")
    Document.objects.all().update(metadata_structure_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0001_initial"),
        ("documents", "0002_fase05_models"),
    ]

    operations = [
        migrations.RunPython(clear_metadata_structure_fk, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Documento",
                "verbose_name_plural": "Documenti",
            },
        ),
        migrations.AlterField(
            model_name="document",
            name="metadata_structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="metadata.metadatastructure",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="version_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name="MetadataStructure",
        ),
    ]
