# Generated by Django 4.2.29 on 2026-03-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_document_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversion",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="thumbnails/%Y/%m/"
            ),
        ),
    ]
