# Generated by Django 4.2.29 on 2026-03-25 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("metadata", "0004_document_template"),
        ("workflows", "0002_raci_matrix"),
        ("documents", "0007_documentversion_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nome del template", max_length=255),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "default_status",
                    models.CharField(
                        choices=[("DRAFT", "Bozza"), ("IN_REVIEW", "In Revisione")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "default_metadata_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Valori predefiniti per i campi metadati",
                    ),
                ),
                (
                    "auto_start_workflow",
                    models.BooleanField(
                        default=False,
                        help_text="Avvia automaticamente il workflow dopo il caricamento",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "allowed_file_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Estensioni ammesse (es. ['pdf']). Vuoto = tutte.",
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.IntegerField(
                        blank=True,
                        help_text="Dimensione massima file in MB. Null = nessun limite.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_document_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_folder",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cartella di destinazione predefinita",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_templates",
                        to="documents.folder",
                    ),
                ),
                (
                    "default_metadata_structure",
                    models.ForeignKey(
                        blank=True,
                        help_text="Struttura metadati predefinita",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_templates",
                        to="metadata.metadatastructure",
                    ),
                ),
                (
                    "default_workflow_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Workflow da avviare automaticamente",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_templates",
                        to="workflows.workflowtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template documento",
                "verbose_name_plural": "Template documenti",
                "ordering": ["name"],
            },
        ),
    ]
