# Generated by Django 4.2.29 on 2026-03-25 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_tenant_organizationalunit_tenant"),
        ("documents", "0008_document_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="organizations.tenant",
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_templates",
                to="organizations.tenant",
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folders",
                to="organizations.tenant",
            ),
        ),
    ]
