# Generated by Django 4.2.29 on 2026-03-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_document_tenant_documenttemplate_tenant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extracted_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Testo estratto (OCR, pdftotext o estrazione nativa)",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="ocr_confidence",
            field=models.FloatField(
                blank=True, help_text="Confidenza OCR media 0-100", null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="ocr_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="document",
            name="ocr_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "In attesa"),
                    ("processing", "In elaborazione"),
                    ("completed", "Completato"),
                    ("failed", "Fallito"),
                    ("not_needed", "Non necessario"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
