# Generated by Django 4.2.29 on 2026-03-12 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0004_document_is_protocolled"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("indexed_at", models.DateTimeField(auto_now=True)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_index",
                        to="documents.document",
                    ),
                ),
                (
                    "document_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.documentversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indice documento",
                "indexes": [
                    models.Index(
                        fields=["document"], name="search_docu_documen_f17556_idx"
                    )
                ],
            },
        ),
    ]
