# Generated by Django 4.2.29 on 2026-03-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentindex",
            name="extraction_method",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Es. ocr, pdftotext, pypdf, docx",
                max_length=30,
            ),
        ),
    ]
