"""
Test fascicolo esteso FASE 22: identifier, cartelle, email, file, close, indice, agid_metadata.
"""
import pytest
from django.contrib.auth import get_user_model
from rest_framework.test import APIClient
from rest_framework import status

from apps.dossiers.models import Dossier, DossierDocument, DossierFolder, DossierEmail, DossierFile
from apps.documents.models import Document, Folder
from apps.organizations.models import OrganizationalUnit

User = get_user_model()


@pytest.fixture
def client():
    return APIClient()


@pytest.fixture
def ou(db):
    return OrganizationalUnit.objects.create(name="UO Test", code="CM")


@pytest.fixture
def user(db):
    u = User.objects.create_user(email="user@test.com", password="test")
    u.role = "APPROVER"
    u.save()
    return u


@pytest.fixture
def dossier_with_ou(db, user, ou):
    # Usa identificatore esplicito per evitare dipendenza da auto-gen nel save (fixture)
    d = Dossier.objects.create(
        title="Fascicolo test",
        identifier="2026/CM/0001",
        description="",
        responsible=user,
        created_by=user,
        organizational_unit=ou,
        status="open",
    )
    return d


@pytest.fixture
def folder(db, user):
    return Folder.objects.create(name="Cartella F", created_by=user)


@pytest.mark.django_db
class TestIdentifierAutoGenerated:
    def test_identifier_auto_generated(self, dossier_with_ou):
        """Il fascicolo con UO ha identificatore nel formato atteso."""
        assert dossier_with_ou.identifier
        assert "/" in dossier_with_ou.identifier
        assert "CM" in dossier_with_ou.identifier

    def test_identifier_format_correct(self, dossier_with_ou):
        """L'identificatore nel formato ANNO/UO/PROGRESSIVO ha tre parti valide."""
        ident = dossier_with_ou.identifier
        assert ident
        parts = ident.split("/")
        assert len(parts) == 3, f"Identificatore atteso ANNO/UO/PROG, ottenuto {ident}"
        assert parts[0].isdigit()
        assert parts[1] == "CM"
        assert parts[2].isdigit() and len(parts[2]) == 4


@pytest.mark.django_db
class TestAddFolder:
    def test_add_folder_to_dossier(self, client, user, dossier_with_ou, folder):
        client.force_authenticate(user=user)
        r = client.post(
            f"/api/dossiers/{dossier_with_ou.id}/add_folder/",
            {"folder_id": str(folder.id)},
            format="json",
        )
        assert r.status_code == 200
        assert DossierFolder.objects.filter(dossier=dossier_with_ou, folder=folder).exists()


@pytest.mark.django_db
class TestAddEmail:
    def test_add_email_to_dossier(self, client, user, dossier_with_ou):
        client.force_authenticate(user=user)
        r = client.post(
            f"/api/dossiers/{dossier_with_ou.id}/add_email/",
            {
                "email_type": "pec",
                "from_address": "a@test.com",
                "to_addresses": ["b@test.com"],
                "subject": "Oggetto",
                "body": "Corpo",
                "received_at": "2026-01-15T10:00:00Z",
            },
            format="json",
        )
        assert r.status_code == 201
        assert DossierEmail.objects.filter(dossier=dossier_with_ou).exists()


@pytest.mark.django_db
class TestUploadFile:
    def test_upload_file_to_dossier(self, client, user, dossier_with_ou):
        from django.core.files.uploadedfile import SimpleUploadedFile
        client.force_authenticate(user=user)
        f = SimpleUploadedFile("test.txt", b"test content", content_type="text/plain")
        r = client.post(
            f"/api/dossiers/{dossier_with_ou.id}/upload_file/",
            {"file": f, "notes": "Note"},
            format="multipart",
        )
        assert r.status_code == 201
        assert DossierFile.objects.filter(dossier=dossier_with_ou).exists()


@pytest.mark.django_db
class TestCloseDossier:
    def test_close_dossier(self, client, user, dossier_with_ou):
        client.force_authenticate(user=user)
        r = client.post(f"/api/dossiers/{dossier_with_ou.id}/close/", {}, format="json")
        assert r.status_code == 200
        dossier_with_ou.refresh_from_db()
        assert dossier_with_ou.status == "closed"
        assert dossier_with_ou.closed_at is not None

    def test_closed_dossier_rejects_new_documents(self, client, user, dossier_with_ou, folder):
        dossier_with_ou.status = "closed"
        dossier_with_ou.save()
        client.force_authenticate(user=user)
        r = client.post(
            f"/api/dossiers/{dossier_with_ou.id}/add_folder/",
            {"folder_id": str(folder.id)},
            format="json",
        )
        assert r.status_code == 400


@pytest.mark.django_db
class TestGenerateIndex:
    def test_generate_index_returns_pdf(self, client, user, dossier_with_ou):
        client.force_authenticate(user=user)
        r = client.get(f"/api/dossiers/{dossier_with_ou.id}/generate_index/")
        assert r.status_code == 200
        assert "application/pdf" in r.get("Content-Type", "")
        assert len(r.content) > 100
        dossier_with_ou.refresh_from_db()
        assert dossier_with_ou.index_generated_at is not None


@pytest.mark.django_db
class TestAgidMetadata:
    def test_agid_metadata_has_required_fields(self, client, user, dossier_with_ou):
        client.force_authenticate(user=user)
        r = client.get(f"/api/dossiers/{dossier_with_ou.id}/agid_metadata/")
        assert r.status_code == 200
        data = r.json()
        assert "identificativo" in data
        assert "oggetto" in data
        assert "responsabile" in data
        assert "stato" in data
        assert "indice_documenti" in data
