# Generated by Django 4.2.29 on 2026-03-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("protocols", "0002_fase09_protocol_counter_and_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocol",
            name="document_file",
            field=models.FileField(
                blank=True,
                help_text="File da timbrare (AGID)",
                null=True,
                upload_to="protocol_docs/",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="protocolcounter",
            unique_together={("organizational_unit", "year")},
        ),
    ]
