# Generated by Django 4.2.29 on 2026-03-25 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_tenant_organizationalunit_tenant"),
        ("protocols", "0004_add_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocols",
                to="organizations.tenant",
            ),
        ),
        migrations.AddField(
            model_name="protocolcounter",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocol_counters",
                to="organizations.tenant",
            ),
        ),
    ]
