# Generated by Django 4.2.29 on 2026-03-25 18:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nome organizzazione", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificativo URL-safe (es. comune-milano)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Dominio personalizzato. Vuoto = subdomain o default.",
                        max_length=255,
                    ),
                ),
                ("logo_url", models.URLField(blank=True, default="")),
                (
                    "primary_color",
                    models.CharField(
                        default="#4f46e5", help_text="Colore primario HEX", max_length=7
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(default=50, help_text="Numero massimo utenti"),
                ),
                (
                    "max_storage_gb",
                    models.IntegerField(default=10, help_text="Storage massimo in GB"),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="organizationalunit",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizational_units",
                to="organizations.tenant",
            ),
        ),
    ]
